import uuid
from typing import List, Dict, Any
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from sqlalchemy.orm import selectinload

from src.insurance.models import InsurancePolicy, InsuranceClaim, AILiabilityEventLog
from src.insurance.schemas import (
    InsurancePolicyCreate,
    InsuranceClaimCreate,
    AILiabilityEventLogCreate,
)


class InsuranceService:
    def __init__(self, db_session: AsyncSession):
        self.db = db_session

    async def create_policy(
        self, policy_data: InsurancePolicyCreate
    ) -> InsurancePolicy:
        # In a real system, policy_number would be generated by a more robust mechanism
        policy_number = f"POL-{uuid.uuid4().hex[:10].upper()}"

        new_policy = InsurancePolicy(**policy_data.dict(), policy_number=policy_number)
        self.db.add(new_policy)
        await self.db.commit()
        await self.db.refresh(new_policy)
        return new_policy

    async def get_policy_by_id(self, policy_id: uuid.UUID) -> InsurancePolicy:
        result = await self.db.execute(
            select(InsurancePolicy)
            .where(InsurancePolicy.id == policy_id)
            .options(selectinload(InsurancePolicy.claims))
        )
        return result.scalars().first()

    async def create_claim(self, claim_data: InsuranceClaimCreate) -> InsuranceClaim:
        new_claim = InsuranceClaim(**claim_data.dict())
        self.db.add(new_claim)
        await self.db.commit()
        await self.db.refresh(new_claim)
        return new_claim

    async def add_event_log_to_claim(
        self, claim_id: uuid.UUID, event_log_data: AILiabilityEventLogCreate
    ) -> AILiabilityEventLog:
        new_log = AILiabilityEventLog(**event_log_data.dict(), claim_id=claim_id)
        self.db.add(new_log)
        await self.db.commit()
        await self.db.refresh(new_log)
        return new_log

    async def get_claim_with_logs(self, claim_id: uuid.UUID) -> InsuranceClaim:
        result = await self.db.execute(
            select(InsuranceClaim)
            .where(InsuranceClaim.id == claim_id)
            .options(selectinload(InsuranceClaim.event_logs))
        )
        return result.scalars().first()

    # Placeholder for the future liability adjudication logic
    async def adjudicate_claim(self, claim_id: uuid.UUID) -> Dict[str, Any]:
        """
        This is where the magic will happen.
        1. Fetch the claim and its associated event logs.
        2. Package the logs into a UATP Capsule.
        3. (Future) Send the capsule to a liability adjudication engine.
        4. Receive the adjudication result (e.g., fault percentage).
        5. Update the claim status and payout amount based on the result.
        """
        claim = await self.get_claim_with_logs(claim_id)
        if not claim:
            return {"error": "Claim not found"}

        # In a real implementation, this would call the Capsule Engine
        capsule_id = f"CAPSULE-{uuid.uuid4().hex}"
        claim.capsule_id = capsule_id

        # Mock adjudication result
        adjudication_result = {
            "fault_assessment": {"vehicle_A": 0.7, "vehicle_B": 0.3},
            "recommended_payout_percentage": 0.7,
        }

        # Update claim based on adjudication
        claim.reason = f"Adjudicated with capsule {capsule_id}. Fault assessment: {adjudication_result['fault_assessment']}"

        await self.db.commit()

        return {
            "claim_id": claim.id,
            "capsule_id": capsule_id,
            "adjudication": adjudication_result,
        }
