"""
Real-time Attribution Monitoring System for UATP Security.

This module implements comprehensive real-time monitoring of attribution
activities with automated alerting, anomaly detection, and threat response
capabilities.

SECURITY FEATURES:
- Real-time stream processing
- Multi-threshold alerting system
- Anomaly detection algorithms
- Automated threat response
- Dashboard and reporting integration
"""

import asyncio
import json
import logging
import queue
import threading
import time
import uuid
from collections import defaultdict, deque
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Set

import numpy as np
from scipy import stats

from src.audit.events import audit_emitter

logger = logging.getLogger(__name__)


class AlertSeverity(str, Enum):
    """Alert severity levels."""

    INFO = "info"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ThreatType(str, Enum):
    """Types of threats detected."""

    ATTRIBUTION_GAMING = "attribution_gaming"
    SYBIL_ATTACK = "sybil_attack"
    COORDINATED_MANIPULATION = "coordinated_manipulation"
    SIMILARITY_SPOOFING = "similarity_spoofing"
    CONFIDENCE_INFLATION = "confidence_inflation"
    LINEAGE_TAMPERING = "lineage_tampering"
    VOLUME_ATTACK = "volume_attack"
    TEMPORAL_ANOMALY = "temporal_anomaly"
    QUALITY_DEGRADATION = "quality_degradation"


@dataclass
class AttributionEvent:
    """Individual attribution event for monitoring."""

    event_id: str
    event_type: str
    timestamp: datetime

    # Attribution data
    source_entity: str
    target_entity: str
    similarity_score: float
    confidence_score: float

    # Context data
    content_hash: str
    conversation_id: Optional[str] = None
    user_id: Optional[str] = None

    # Security metadata
    gaming_detected: bool = False
    anomaly_score: float = 0.0
    risk_factors: List[str] = field(default_factory=list)

    # Processing metadata
    processed: bool = False
    alerts_generated: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Convert event to dictionary."""
        return {
            "event_id": self.event_id,
            "event_type": self.event_type,
            "timestamp": self.timestamp.isoformat(),
            "source_entity": self.source_entity,
            "target_entity": self.target_entity,
            "similarity_score": self.similarity_score,
            "confidence_score": self.confidence_score,
            "content_hash": self.content_hash,
            "conversation_id": self.conversation_id,
            "user_id": self.user_id,
            "gaming_detected": self.gaming_detected,
            "anomaly_score": self.anomaly_score,
            "risk_factors": self.risk_factors,
            "processed": self.processed,
            "alerts_generated": self.alerts_generated,
        }


@dataclass
class SecurityAlert:
    """Security alert generated by monitoring system."""

    alert_id: str
    severity: AlertSeverity
    threat_type: ThreatType

    # Alert details
    title: str
    description: str
    affected_entities: List[str]
    evidence: Dict[str, Any]

    # Timing
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    first_occurrence: Optional[datetime] = None

    # Response tracking
    acknowledged: bool = False
    resolved: bool = False
    actions_taken: List[str] = field(default_factory=list)

    # Metrics
    confidence: float = 0.0
    impact_assessment: str = ""

    def to_dict(self) -> Dict[str, Any]:
        """Convert alert to dictionary."""
        return {
            "alert_id": self.alert_id,
            "severity": self.severity.value,
            "threat_type": self.threat_type.value,
            "title": self.title,
            "description": self.description,
            "affected_entities": self.affected_entities,
            "evidence": self.evidence,
            "timestamp": self.timestamp.isoformat(),
            "first_occurrence": self.first_occurrence.isoformat()
            if self.first_occurrence
            else None,
            "acknowledged": self.acknowledged,
            "resolved": self.resolved,
            "actions_taken": self.actions_taken,
            "confidence": self.confidence,
            "impact_assessment": self.impact_assessment,
        }


@dataclass
class MonitoringRule:
    """Rule for monitoring attribution activities."""

    rule_id: str
    rule_name: str
    enabled: bool = True

    # Conditions
    conditions: Dict[str, Any] = field(default_factory=dict)
    threshold_values: Dict[str, float] = field(default_factory=dict)

    # Actions
    alert_severity: AlertSeverity = AlertSeverity.MEDIUM
    alert_title: str = ""
    alert_description: str = ""

    # Response actions
    auto_block_entities: bool = False
    auto_flag_attributions: bool = False
    notify_administrators: bool = True

    # Performance tracking
    rule_triggers: int = 0
    false_positives: int = 0
    last_triggered: Optional[datetime] = None

    def evaluate(self, event: AttributionEvent) -> bool:
        """Evaluate if this rule triggers for the given event."""

        for condition, expected_value in self.conditions.items():
            if condition == "similarity_threshold":
                if event.similarity_score < expected_value:
                    return False
            elif condition == "confidence_threshold":
                if event.confidence_score < expected_value:
                    return False
            elif condition == "gaming_detected":
                if event.gaming_detected != expected_value:
                    return False
            elif condition == "anomaly_threshold":
                if event.anomaly_score < expected_value:
                    return False
            elif condition == "risk_factor_present":
                if expected_value not in event.risk_factors:
                    return False

        return True


class AttributionMonitor:
    """Real-time attribution monitoring system."""

    def __init__(self):
        # Event processing
        self.event_queue = queue.Queue(maxsize=10000)
        self.processing_thread = None
        self.running = False

        # Event storage
        self.recent_events = deque(maxlen=50000)  # Last 50k events
        self.event_index: Dict[str, AttributionEvent] = {}

        # Alert management
        self.active_alerts: Dict[str, SecurityAlert] = {}
        self.alert_history = deque(maxlen=10000)

        # Monitoring rules
        self.monitoring_rules: Dict[str, MonitoringRule] = {}
        self._initialize_default_rules()

        # Real-time statistics
        self.realtime_stats = {
            "events_per_minute": deque(maxlen=60),  # Per-minute counts
            "alerts_per_hour": deque(maxlen=24),  # Per-hour counts
            "threat_types_24h": defaultdict(int),
            "top_entities_24h": defaultdict(int),
            "gaming_detection_rate": 0.0,
            "average_anomaly_score": 0.0,
        }

        # Anomaly detection
        self.anomaly_detectors = {
            "volume": self._detect_volume_anomaly,
            "timing": self._detect_timing_anomaly,
            "quality": self._detect_quality_anomaly,
            "entity_behavior": self._detect_entity_behavior_anomaly,
        }

        # Alert callbacks
        self.alert_callbacks: List[Callable[[SecurityAlert], None]] = []

        # Performance metrics
        self.metrics = {
            "total_events_processed": 0,
            "total_alerts_generated": 0,
            "gaming_attempts_detected": 0,
            "sybil_attacks_detected": 0,
            "coordinated_attacks_detected": 0,
            "false_positive_rate": 0.0,
            "average_processing_time_ms": 0.0,
        }

        logger.info("Attribution Monitor initialized")

    def start_monitoring(self):
        """Start real-time monitoring."""

        if self.running:
            logger.warning("Monitor already running")
            return

        self.running = True
        self.processing_thread = threading.Thread(
            target=self._process_events, daemon=True
        )
        self.processing_thread.start()

        # Start statistics collection
        self._start_statistics_collection()

        logger.info("Attribution monitoring started")

    def stop_monitoring(self):
        """Stop real-time monitoring."""

        self.running = False

        if self.processing_thread and self.processing_thread.is_alive():
            self.processing_thread.join(timeout=5.0)

        logger.info("Attribution monitoring stopped")

    def submit_attribution_event(
        self,
        event_type: str,
        source_entity: str,
        target_entity: str,
        similarity_score: float,
        confidence_score: float,
        content_hash: str,
        context: Dict[str, Any] = None,
    ) -> str:
        """Submit attribution event for monitoring."""

        context = context or {}

        event = AttributionEvent(
            event_id=f"attr_event_{uuid.uuid4()}",
            event_type=event_type,
            timestamp=datetime.now(timezone.utc),
            source_entity=source_entity,
            target_entity=target_entity,
            similarity_score=similarity_score,
            confidence_score=confidence_score,
            content_hash=content_hash,
            conversation_id=context.get("conversation_id"),
            user_id=context.get("user_id"),
            gaming_detected=context.get("gaming_detected", False),
            anomaly_score=context.get("anomaly_score", 0.0),
            risk_factors=context.get("risk_factors", []),
        )

        try:
            self.event_queue.put_nowait(event)
            return event.event_id
        except queue.Full:
            logger.error("Event queue full, dropping event")
            return ""

    def _process_events(self):
        """Main event processing loop."""

        while self.running:
            try:
                # Process events in batches
                events_batch = []

                # Collect batch of events (up to 100 or 1 second timeout)
                start_time = time.time()
                while len(events_batch) < 100 and (time.time() - start_time) < 1.0:
                    try:
                        event = self.event_queue.get(timeout=0.1)
                        events_batch.append(event)
                    except queue.Empty:
                        break

                if events_batch:
                    processing_start = time.time()
                    self._process_event_batch(events_batch)
                    processing_time = (time.time() - processing_start) * 1000

                    # Update performance metrics
                    self.metrics["total_events_processed"] += len(events_batch)
                    self.metrics["average_processing_time_ms"] = (
                        self.metrics["average_processing_time_ms"] * 0.9
                    ) + (processing_time * 0.1)

            except Exception as e:
                logger.error(f"Error in event processing: {e}")
                time.sleep(0.1)

    def _process_event_batch(self, events: List[AttributionEvent]):
        """Process a batch of attribution events."""

        for event in events:
            # Store event
            self.recent_events.append(event)
            self.event_index[event.event_id] = event

            # Run anomaly detection
            self._run_anomaly_detection(event)

            # Evaluate monitoring rules
            triggered_rules = self._evaluate_monitoring_rules(event)

            # Generate alerts if needed
            if triggered_rules:
                self._generate_alerts(event, triggered_rules)

            # Update real-time statistics
            self._update_realtime_stats(event)

            # Mark as processed
            event.processed = True

        # Perform batch analysis
        self._perform_batch_analysis(events)

    def _run_anomaly_detection(self, event: AttributionEvent):
        """Run anomaly detection on event."""

        anomaly_scores = []

        # Run all anomaly detectors
        for detector_name, detector_func in self.anomaly_detectors.items():
            try:
                score = detector_func(event)
                anomaly_scores.append(score)
            except Exception as e:
                logger.error(f"Error in {detector_name} anomaly detector: {e}")

        # Combine anomaly scores
        if anomaly_scores:
            event.anomaly_score = max(anomaly_scores)

            # Flag high anomaly events
            if event.anomaly_score > 0.8:
                event.risk_factors.append("high_anomaly_score")

    def _detect_volume_anomaly(self, event: AttributionEvent) -> float:
        """Detect volume-based anomalies."""

        # Count recent events from same entity
        recent_cutoff = datetime.now(timezone.utc) - timedelta(minutes=10)
        recent_count = sum(
            1
            for e in self.recent_events
            if (
                e.source_entity == event.source_entity
                or e.target_entity == event.target_entity
            )
            and e.timestamp > recent_cutoff
        )

        # Anomaly if more than 50 events in 10 minutes
        if recent_count > 50:
            return min(1.0, recent_count / 100.0)

        return 0.0

    def _detect_timing_anomaly(self, event: AttributionEvent) -> float:
        """Detect timing-based anomalies."""

        # Check for burst patterns
        entity_events = [
            e
            for e in self.recent_events
            if e.source_entity == event.source_entity
            or e.target_entity == event.target_entity
        ]

        if len(entity_events) < 5:
            return 0.0

        # Calculate inter-event intervals
        intervals = []
        for i in range(1, len(entity_events)):
            interval = (
                entity_events[i].timestamp - entity_events[i - 1].timestamp
            ).total_seconds()
            intervals.append(interval)

        if intervals:
            # Check for suspiciously regular intervals (bot-like)
            interval_std = np.std(intervals)
            if interval_std < 1.0:  # Very regular timing
                return 0.7

            # Check for burst activity
            avg_interval = np.mean(intervals)
            if avg_interval < 5.0:  # Less than 5 seconds between events
                return 0.6

        return 0.0

    def _detect_quality_anomaly(self, event: AttributionEvent) -> float:
        """Detect quality degradation anomalies."""

        # Check for consistently low similarity scores
        entity_events = [
            e
            for e in self.recent_events[-100:]  # Last 100 events
            if e.source_entity == event.source_entity
        ]

        if len(entity_events) >= 10:
            recent_similarities = [e.similarity_score for e in entity_events[-10:]]
            avg_similarity = np.mean(recent_similarities)

            # Anomaly if average similarity is very low
            if avg_similarity < 0.2:
                return 0.8

            # Check for artificial consistency
            if np.std(recent_similarities) < 0.01:
                return 0.6

        return 0.0

    def _detect_entity_behavior_anomaly(self, event: AttributionEvent) -> float:
        """Detect entity behavioral anomalies."""

        # Count unique interaction partners
        entity_partners = set()
        for e in self.recent_events[-1000:]:  # Last 1000 events
            if e.source_entity == event.source_entity:
                entity_partners.add(e.target_entity)
            elif e.target_entity == event.source_entity:
                entity_partners.add(e.source_entity)

        # Anomaly if interacting with too many partners (potential Sybil)
        if len(entity_partners) > 100:
            return min(1.0, len(entity_partners) / 200.0)

        return 0.0

    def _evaluate_monitoring_rules(
        self, event: AttributionEvent
    ) -> List[MonitoringRule]:
        """Evaluate monitoring rules against event."""

        triggered_rules = []

        for rule in self.monitoring_rules.values():
            if not rule.enabled:
                continue

            try:
                if rule.evaluate(event):
                    rule.rule_triggers += 1
                    rule.last_triggered = datetime.now(timezone.utc)
                    triggered_rules.append(rule)
            except Exception as e:
                logger.error(f"Error evaluating rule {rule.rule_id}: {e}")

        return triggered_rules

    def _generate_alerts(
        self, event: AttributionEvent, triggered_rules: List[MonitoringRule]
    ):
        """Generate security alerts based on triggered rules."""

        for rule in triggered_rules:
            alert_id = f"alert_{uuid.uuid4()}"

            # Determine threat type based on rule
            threat_type = self._determine_threat_type(rule, event)

            # Create alert
            alert = SecurityAlert(
                alert_id=alert_id,
                severity=rule.alert_severity,
                threat_type=threat_type,
                title=rule.alert_title or f"Rule triggered: {rule.rule_name}",
                description=rule.alert_description
                or f"Monitoring rule {rule.rule_name} was triggered",
                affected_entities=[event.source_entity, event.target_entity],
                evidence={
                    "triggering_event": event.to_dict(),
                    "rule_id": rule.rule_id,
                    "rule_name": rule.rule_name,
                    "anomaly_score": event.anomaly_score,
                    "risk_factors": event.risk_factors,
                },
                confidence=self._calculate_alert_confidence(rule, event),
            )

            # Store alert
            self.active_alerts[alert_id] = alert
            self.alert_history.append(alert)

            # Update event
            event.alerts_generated.append(alert_id)

            # Execute automated responses
            if rule.auto_block_entities:
                self._auto_block_entities(alert.affected_entities)

            if rule.auto_flag_attributions:
                self._auto_flag_attribution(event)

            # Notify callbacks
            for callback in self.alert_callbacks:
                try:
                    callback(alert)
                except Exception as e:
                    logger.error(f"Error in alert callback: {e}")

            # Emit security event
            audit_emitter.emit_security_event(
                "realtime_security_alert_generated",
                {
                    "alert_id": alert_id,
                    "severity": alert.severity.value,
                    "threat_type": alert.threat_type.value,
                    "affected_entities": alert.affected_entities,
                    "confidence": alert.confidence,
                },
            )

            self.metrics["total_alerts_generated"] += 1

    def _perform_batch_analysis(self, events: List[AttributionEvent]):
        """Perform analysis on batch of events."""

        if len(events) < 5:
            return

        # Look for coordinated patterns
        self._detect_coordinated_activity(events)

        # Look for systematic gaming
        self._detect_systematic_gaming(events)

        # Update threat statistics
        self._update_threat_statistics(events)

    def _detect_coordinated_activity(self, events: List[AttributionEvent]):
        """Detect coordinated activity patterns in event batch."""

        # Group events by time windows
        time_windows = defaultdict(list)
        for event in events:
            time_key = event.timestamp.replace(second=0, microsecond=0)
            time_windows[time_key].append(event)

        # Look for suspicious coordination
        for time_key, time_events in time_windows.items():
            if len(time_events) >= 5:
                # Check if events involve overlapping entities
                entities = set()
                for event in time_events:
                    entities.add(event.source_entity)
                    entities.add(event.target_entity)

                # If many events but few unique entities, might be coordinated
                if len(time_events) > len(entities) * 1.5:
                    self._generate_coordination_alert(time_events, entities)

    def _detect_systematic_gaming(self, events: List[AttributionEvent]):
        """Detect systematic gaming patterns."""

        # Look for threshold targeting
        confidence_scores = [e.confidence_score for e in events]
        if len(confidence_scores) >= 10:
            # Check clustering around thresholds
            thresholds = [0.2, 0.5, 0.8]
            for threshold in thresholds:
                near_threshold = [
                    s for s in confidence_scores if abs(s - threshold) < 0.05
                ]
                if len(near_threshold) / len(confidence_scores) > 0.4:
                    self._generate_gaming_alert(
                        "threshold_targeting", events, threshold
                    )

    def _initialize_default_rules(self):
        """Initialize default monitoring rules."""

        # High similarity gaming rule
        self.monitoring_rules["high_similarity_gaming"] = MonitoringRule(
            rule_id="high_similarity_gaming",
            rule_name="High Similarity Gaming Detection",
            conditions={"similarity_threshold": 0.95, "gaming_detected": True},
            alert_severity=AlertSeverity.HIGH,
            alert_title="High Similarity Gaming Detected",
            alert_description="Detected potential gaming with unusually high similarity scores",
            auto_flag_attributions=True,
        )

        # Volume attack rule
        self.monitoring_rules["volume_attack"] = MonitoringRule(
            rule_id="volume_attack",
            rule_name="Volume Attack Detection",
            conditions={"anomaly_threshold": 0.8},
            threshold_values={"events_per_minute": 20},
            alert_severity=AlertSeverity.CRITICAL,
            alert_title="Volume Attack Detected",
            alert_description="Detected high-volume attribution attack",
            auto_block_entities=True,
            notify_administrators=True,
        )

        # Confidence inflation rule
        self.monitoring_rules["confidence_inflation"] = MonitoringRule(
            rule_id="confidence_inflation",
            rule_name="Confidence Inflation Detection",
            conditions={
                "confidence_threshold": 0.95,
                "risk_factor_present": "confidence_exceeds_similarity",
            },
            alert_severity=AlertSeverity.MEDIUM,
            alert_title="Confidence Score Inflation",
            alert_description="Detected artificial inflation of confidence scores",
            auto_flag_attributions=True,
        )

        # Sybil attack rule
        self.monitoring_rules["sybil_attack"] = MonitoringRule(
            rule_id="sybil_attack",
            rule_name="Sybil Attack Detection",
            conditions={"risk_factor_present": "multiple_similar_entities"},
            alert_severity=AlertSeverity.CRITICAL,
            alert_title="Sybil Attack Detected",
            alert_description="Detected potential Sybil attack with multiple coordinated entities",
            auto_block_entities=True,
            notify_administrators=True,
        )

    def _determine_threat_type(
        self, rule: MonitoringRule, event: AttributionEvent
    ) -> ThreatType:
        """Determine threat type based on rule and event."""

        if "gaming" in rule.rule_id.lower():
            return ThreatType.ATTRIBUTION_GAMING
        elif "sybil" in rule.rule_id.lower():
            return ThreatType.SYBIL_ATTACK
        elif "volume" in rule.rule_id.lower():
            return ThreatType.VOLUME_ATTACK
        elif "confidence" in rule.rule_id.lower():
            return ThreatType.CONFIDENCE_INFLATION
        elif "similarity" in rule.rule_id.lower():
            return ThreatType.SIMILARITY_SPOOFING
        elif event.gaming_detected:
            return ThreatType.ATTRIBUTION_GAMING
        else:
            return ThreatType.TEMPORAL_ANOMALY

    def _calculate_alert_confidence(
        self, rule: MonitoringRule, event: AttributionEvent
    ) -> float:
        """Calculate confidence score for alert."""

        confidence = 0.5  # Base confidence

        # Increase based on anomaly score
        confidence += event.anomaly_score * 0.3

        # Increase based on gaming detection
        if event.gaming_detected:
            confidence += 0.2

        # Increase based on number of risk factors
        confidence += len(event.risk_factors) * 0.1

        # Adjust based on rule historical accuracy
        if rule.rule_triggers > 0:
            accuracy = 1.0 - (rule.false_positives / rule.rule_triggers)
            confidence *= accuracy

        return min(1.0, confidence)

    def _auto_block_entities(self, entity_ids: List[str]):
        """Automatically block entities."""

        for entity_id in entity_ids:
            # This would integrate with the actual blocking system
            audit_emitter.emit_security_event(
                "entity_auto_blocked",
                {
                    "entity_id": entity_id,
                    "reason": "automatic_threat_response",
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                },
            )

        logger.warning(f"Auto-blocked entities: {entity_ids}")

    def _auto_flag_attribution(self, event: AttributionEvent):
        """Automatically flag attribution for review."""

        audit_emitter.emit_security_event(
            "attribution_auto_flagged",
            {
                "event_id": event.event_id,
                "source_entity": event.source_entity,
                "target_entity": event.target_entity,
                "reason": "automatic_threat_response",
            },
        )

    def _generate_coordination_alert(
        self, events: List[AttributionEvent], entities: Set[str]
    ):
        """Generate alert for coordinated activity."""

        alert_id = f"coord_alert_{uuid.uuid4()}"

        alert = SecurityAlert(
            alert_id=alert_id,
            severity=AlertSeverity.HIGH,
            threat_type=ThreatType.COORDINATED_MANIPULATION,
            title="Coordinated Attribution Activity Detected",
            description=f"Detected {len(events)} coordinated attribution events involving {len(entities)} entities",
            affected_entities=list(entities),
            evidence={
                "event_count": len(events),
                "entity_count": len(entities),
                "time_window": "1 minute",
                "event_ids": [e.event_id for e in events],
            },
            confidence=0.8,
        )

        self.active_alerts[alert_id] = alert
        self.alert_history.append(alert)
        self.metrics["coordinated_attacks_detected"] += 1

    def _generate_gaming_alert(
        self, gaming_type: str, events: List[AttributionEvent], threshold: float
    ):
        """Generate alert for gaming activity."""

        alert_id = f"gaming_alert_{uuid.uuid4()}"

        alert = SecurityAlert(
            alert_id=alert_id,
            severity=AlertSeverity.MEDIUM,
            threat_type=ThreatType.ATTRIBUTION_GAMING,
            title=f"Attribution Gaming Detected: {gaming_type}",
            description=f"Detected {gaming_type} gaming pattern targeting threshold {threshold}",
            affected_entities=list(
                set(
                    [e.source_entity for e in events]
                    + [e.target_entity for e in events]
                )
            ),
            evidence={
                "gaming_type": gaming_type,
                "threshold_targeted": threshold,
                "event_count": len(events),
                "event_ids": [e.event_id for e in events],
            },
            confidence=0.7,
        )

        self.active_alerts[alert_id] = alert
        self.alert_history.append(alert)
        self.metrics["gaming_attempts_detected"] += 1

    def _update_realtime_stats(self, event: AttributionEvent):
        """Update real-time statistics."""

        current_minute = datetime.now(timezone.utc).replace(second=0, microsecond=0)

        # Update events per minute
        if (
            not self.realtime_stats["events_per_minute"]
            or self.realtime_stats["events_per_minute"][-1][0] != current_minute
        ):
            self.realtime_stats["events_per_minute"].append((current_minute, 1))
        else:
            last_entry = self.realtime_stats["events_per_minute"][-1]
            self.realtime_stats["events_per_minute"][-1] = (
                last_entry[0],
                last_entry[1] + 1,
            )

        # Update entity activity
        self.realtime_stats["top_entities_24h"][event.source_entity] += 1
        self.realtime_stats["top_entities_24h"][event.target_entity] += 1

        # Update gaming detection rate
        recent_gaming_events = sum(
            1 for e in list(self.recent_events)[-1000:] if e.gaming_detected
        )
        self.realtime_stats["gaming_detection_rate"] = recent_gaming_events / min(
            1000, len(self.recent_events)
        )

        # Update average anomaly score
        recent_anomaly_scores = [
            e.anomaly_score for e in list(self.recent_events)[-1000:]
        ]
        if recent_anomaly_scores:
            self.realtime_stats["average_anomaly_score"] = np.mean(
                recent_anomaly_scores
            )

    def _update_threat_statistics(self, events: List[AttributionEvent]):
        """Update threat type statistics."""

        for event in events:
            if event.gaming_detected:
                self.realtime_stats["threat_types_24h"]["gaming"] += 1

            if event.anomaly_score > 0.8:
                self.realtime_stats["threat_types_24h"]["anomaly"] += 1

            if "sybil" in event.risk_factors:
                self.realtime_stats["threat_types_24h"]["sybil"] += 1

    def _start_statistics_collection(self):
        """Start background statistics collection."""

        def collect_stats():
            while self.running:
                try:
                    # Clean up old statistics
                    cutoff_24h = datetime.now(timezone.utc) - timedelta(hours=24)

                    # Clean up entity statistics
                    entities_to_remove = []
                    for entity_id in self.realtime_stats["top_entities_24h"]:
                        # This would check last activity time if we had it
                        pass

                    # Sleep for 1 minute
                    time.sleep(60)

                except Exception as e:
                    logger.error(f"Error in statistics collection: {e}")
                    time.sleep(60)

        stats_thread = threading.Thread(target=collect_stats, daemon=True)
        stats_thread.start()

    def add_monitoring_rule(self, rule: MonitoringRule):
        """Add custom monitoring rule."""

        self.monitoring_rules[rule.rule_id] = rule
        logger.info(f"Added monitoring rule: {rule.rule_name}")

    def remove_monitoring_rule(self, rule_id: str):
        """Remove monitoring rule."""

        if rule_id in self.monitoring_rules:
            del self.monitoring_rules[rule_id]
            logger.info(f"Removed monitoring rule: {rule_id}")

    def add_alert_callback(self, callback: Callable[[SecurityAlert], None]):
        """Add callback for alert notifications."""

        self.alert_callbacks.append(callback)

    def acknowledge_alert(self, alert_id: str, user_id: str = None):
        """Acknowledge a security alert."""

        if alert_id in self.active_alerts:
            alert = self.active_alerts[alert_id]
            alert.acknowledged = True
            alert.actions_taken.append(f"Acknowledged by {user_id or 'system'}")

            audit_emitter.emit_security_event(
                "security_alert_acknowledged",
                {
                    "alert_id": alert_id,
                    "acknowledged_by": user_id,
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                },
            )

    def resolve_alert(
        self, alert_id: str, resolution_notes: str = "", user_id: str = None
    ):
        """Resolve a security alert."""

        if alert_id in self.active_alerts:
            alert = self.active_alerts[alert_id]
            alert.resolved = True
            alert.actions_taken.append(
                f"Resolved by {user_id or 'system'}: {resolution_notes}"
            )

            # Move to history only
            del self.active_alerts[alert_id]

            audit_emitter.emit_security_event(
                "security_alert_resolved",
                {
                    "alert_id": alert_id,
                    "resolved_by": user_id,
                    "resolution_notes": resolution_notes,
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                },
            )

    def get_active_alerts(
        self, severity_filter: Optional[AlertSeverity] = None
    ) -> List[SecurityAlert]:
        """Get active security alerts."""

        alerts = list(self.active_alerts.values())

        if severity_filter:
            alerts = [a for a in alerts if a.severity == severity_filter]

        # Sort by severity and timestamp
        severity_order = {
            AlertSeverity.CRITICAL: 5,
            AlertSeverity.HIGH: 4,
            AlertSeverity.MEDIUM: 3,
            AlertSeverity.LOW: 2,
            AlertSeverity.INFO: 1,
        }

        alerts.sort(
            key=lambda a: (severity_order[a.severity], a.timestamp), reverse=True
        )
        return alerts

    def get_monitoring_dashboard_data(self) -> Dict[str, Any]:
        """Get data for monitoring dashboard."""

        # Recent activity metrics
        recent_events_count = len(
            [
                e
                for e in self.recent_events
                if e.timestamp > datetime.now(timezone.utc) - timedelta(hours=1)
            ]
        )

        # Active alerts by severity
        alert_counts = defaultdict(int)
        for alert in self.active_alerts.values():
            alert_counts[alert.severity.value] += 1

        # Top entities by activity
        top_entities = sorted(
            self.realtime_stats["top_entities_24h"].items(),
            key=lambda x: x[1],
            reverse=True,
        )[:10]

        return {
            "current_timestamp": datetime.now(timezone.utc).isoformat(),
            "monitoring_status": "active" if self.running else "stopped",
            "recent_activity": {
                "events_last_hour": recent_events_count,
                "events_per_minute": list(self.realtime_stats["events_per_minute"])[
                    -10:
                ],
                "gaming_detection_rate": self.realtime_stats["gaming_detection_rate"],
                "average_anomaly_score": self.realtime_stats["average_anomaly_score"],
            },
            "alerts": {
                "active_count": len(self.active_alerts),
                "by_severity": dict(alert_counts),
                "recent_alerts": [a.to_dict() for a in list(self.alert_history)[-10:]],
            },
            "threat_landscape": {
                "threat_types_24h": dict(self.realtime_stats["threat_types_24h"]),
                "top_entities": top_entities,
            },
            "performance_metrics": self.metrics.copy(),
            "monitoring_rules": {
                "total_rules": len(self.monitoring_rules),
                "enabled_rules": len(
                    [r for r in self.monitoring_rules.values() if r.enabled]
                ),
            },
        }

    def get_monitor_statistics(self) -> Dict[str, Any]:
        """Get comprehensive monitor statistics."""

        # Rule statistics
        rule_stats = {}
        for rule_id, rule in self.monitoring_rules.items():
            rule_stats[rule_id] = {
                "enabled": rule.enabled,
                "triggers": rule.rule_triggers,
                "false_positives": rule.false_positives,
                "last_triggered": rule.last_triggered.isoformat()
                if rule.last_triggered
                else None,
                "accuracy": 1.0 - (rule.false_positives / max(1, rule.rule_triggers)),
            }

        return {
            "performance_metrics": self.metrics.copy(),
            "realtime_statistics": {
                "recent_events_count": len(self.recent_events),
                "active_alerts_count": len(self.active_alerts),
                "alert_history_count": len(self.alert_history),
                "monitoring_rules_count": len(self.monitoring_rules),
            },
            "rule_statistics": rule_stats,
            "system_status": {
                "monitoring_active": self.running,
                "event_queue_size": self.event_queue.qsize(),
                "processing_thread_alive": self.processing_thread.is_alive()
                if self.processing_thread
                else False,
            },
        }


# Global attribution monitor instance
attribution_monitor = AttributionMonitor()
