"""Create capsules table (SQLite compatible)

Revision ID: 0eb20474e8c4
Revises:
Create Date: 2025-07-06 20:26:44.476153

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0eb20474e8c4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "capsules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("capsule_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("capsule_type", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("input_data", sa.JSON(), nullable=True),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("reasoning", sa.JSON(), nullable=True),
        sa.Column("model_version", sa.String(), nullable=True),
        sa.Column("parent_capsule_id", sa.String(), nullable=True),
        sa.Column("hash", sa.String(), nullable=False),
        sa.Column("signature", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_capsule_id"],
            ["capsules.capsule_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("capsules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_capsules_agent_id"), ["agent_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_capsules_capsule_id"), ["capsule_id"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_capsules_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("capsules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_capsules_id"))
        batch_op.drop_index(batch_op.f("ix_capsules_capsule_id"))
        batch_op.drop_index(batch_op.f("ix_capsules_agent_id"))

    op.drop_table("capsules")
    # ### end Alembic commands ###
