'use client';

import { Badge } from '@/components/ui/badge';
import {
  CheckCircle,
  Shield,
  Lock,
  Lightbulb,
  Brain,
  HelpCircle,
  User,
  Clock,
} from 'lucide-react';

type ProofLevel =
  | 'tool_verified'
  | 'artifact_verified'
  | 'crypto_verified'
  | 'derived'
  | 'heuristic'
  | 'model_generated'
  | 'speculative'
  | 'user_asserted'
  | 'untested';

interface ProofLevelBadgeProps {
  proofLevel: ProofLevel | string;
  showLabel?: boolean;
  size?: 'sm' | 'md';
}

const proofLevelConfig: Record<
  ProofLevel,
  {
    label: string;
    icon: React.ComponentType<{ className?: string }>;
    className: string;
    description: string;
  }
> = {
  tool_verified: {
    label: 'Tool Verified',
    icon: CheckCircle,
    className: 'bg-green-100 text-green-800 border-green-300',
    description: 'Verified by tool execution',
  },
  artifact_verified: {
    label: 'Artifact Verified',
    icon: Shield,
    className: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    description: 'Verified from file hash, git commit, etc.',
  },
  crypto_verified: {
    label: 'Crypto Verified',
    icon: Lock,
    className: 'bg-blue-100 text-blue-800 border-blue-300',
    description: 'Cryptographically verified (signature, hash)',
  },
  derived: {
    label: 'Derived',
    icon: Lightbulb,
    className: 'bg-purple-100 text-purple-800 border-purple-300',
    description: 'Derived from verified facts through inference',
  },
  heuristic: {
    label: 'Heuristic',
    icon: Brain,
    className: 'bg-yellow-100 text-yellow-800 border-yellow-300',
    description: 'Based on heuristics or patterns (not calibrated)',
  },
  model_generated: {
    label: 'Model Generated',
    icon: Brain,
    className: 'bg-orange-100 text-orange-800 border-orange-300',
    description: 'Generated by AI model (unverified)',
  },
  speculative: {
    label: 'Speculative',
    icon: HelpCircle,
    className: 'bg-red-100 text-red-800 border-red-300',
    description: 'Speculative or uncertain',
  },
  user_asserted: {
    label: 'User Asserted',
    icon: User,
    className: 'bg-gray-100 text-gray-800 border-gray-300',
    description: 'Asserted by user without verification',
  },
  untested: {
    label: 'Untested',
    icon: Clock,
    className: 'bg-gray-100 text-gray-600 border-gray-300',
    description: 'Not yet tested or verified',
  },
};

export function ProofLevelBadge({
  proofLevel,
  showLabel = true,
  size = 'sm',
}: ProofLevelBadgeProps) {
  const config = proofLevelConfig[proofLevel as ProofLevel] || {
    label: proofLevel,
    icon: HelpCircle,
    className: 'bg-gray-100 text-gray-600 border-gray-300',
    description: 'Unknown proof level',
  };

  const Icon = config.icon;
  const iconSize = size === 'sm' ? 'h-3 w-3' : 'h-4 w-4';
  const textSize = size === 'sm' ? 'text-xs' : 'text-sm';

  return (
    <Badge
      variant="outline"
      className={`${config.className} ${textSize} inline-flex items-center gap-1`}
      title={config.description}
    >
      <Icon className={iconSize} />
      {showLabel && <span>{config.label}</span>}
    </Badge>
  );
}

// Helper component to show proof level with explanation
export function ProofLevelExplainer({ proofLevel }: { proofLevel: ProofLevel | string }) {
  const config = proofLevelConfig[proofLevel as ProofLevel];
  if (!config) return null;

  return (
    <div className="flex items-start gap-2 text-xs text-gray-600">
      <ProofLevelBadge proofLevel={proofLevel} size="sm" />
      <span className="text-gray-500">{config.description}</span>
    </div>
  );
}
